### ISSUE TITLE
Private Tab stills appear on a private browsing window and breaks it when used

### ISSUE THREAD

**Issue by charlesmilette** [Infocatcher/Private_Tab#209]
The normal "Open in a new tab" isn't here, only Private Tab's is here, so I can't open link in a new tab if this isn't the web page's normal behavior.  
Plus, what's the point of a private tab in a private window? Fully preventing the addon from firing up in the startup code when a window is private will prevent any conflict and issue with private browsing mode.

[Video](http://fr.tinypic.com/r/2z3tn5f/9)

**Comment by charlesmilette** [comment]
Also, the same broken behavior happens when I right-click a link and then open it in a new tab when i'm currently in a private tab.

**Comment by Infocatcher** [comment]
Looks like broken behavior appears due to #208... And broken not only in private window.

It's possible to create a normal tab in private window (using "Private Tab" checkbox in tab context menu or using drag-and-drop from another window).
Also private flag for window can be changed on the fly...

Also you can tweak appearance using styles:
https://github.com/Infocatcher/Private_Tab#styles
To hide "File - New Private Tab" and "New Private Tab" button:
```css
#main-window[privateTab-isPrivate] #privateTab-menu-openNewPrivateTab,
#main-window[privateTab-isPrivate] #privateTab-afterTabs-openNewPrivateTab,
#main-window[privateTab-isPrivate] #privateTab-toolbar-openNewPrivateTab {
	display: none !important;
}
```

**Comment by charlesmilette** [comment]
That styles works, but doesn't hides the "Private Tab" toggle in context for a tab, and there's still a blank tab when I right-click and press "Open in a new private tab". I also noticed, the blank tab also appears when I do the same thing in a private tab.

**Comment by Infocatcher** [comment]
> but doesn't hides the "Private Tab" toggle in context for a tab

This is `#privateTab-tabContext-toggleTabPrivate`, so it's easy th hide it:
```css
#main-window[privateTab-isPrivate] #privateTab-menu-openNewPrivateTab,
#main-window[privateTab-isPrivate] #privateTab-afterTabs-openNewPrivateTab,
#main-window[privateTab-isPrivate] #privateTab-toolbar-openNewPrivateTab,
#main-window[privateTab-isPrivate] #privateTab-tabContext-toggleTabPrivate {
	display: none !important;
}
```

> and there's still a blank tab when I right-click and press "Open in a new private tab". I also noticed, the blank tab also appears when I do the same thing in a private tab.

Yes, some things are broken now in Firefox 47a (#208).
Something went wrong with `.documentURIObject` from CPOW, that used for HTTP referrer.
