### ISSUE TITLE
[Ask] The icon not same?

### ISSUE THREAD

**Issue by DhannyNara** [Infocatcher/Private_Tab#258]
- Can you tell me why the icon is not same?
the blue and red.
![Screenshot](https://cloud.githubusercontent.com/assets/5054847/24837880/73d96d1a-1d70-11e7-964f-0e11ea223875.jpg)

**Comment by Infocatcher** [comment]
Icon for Private Tab button was added before Firefox 29 (with Australis and that customizable menu).

Style for <a href="http://kb.mozillazine.org/UserChrome.css">userChrome.css</a>/<a href="https://addons.mozilla.org/addon/stylish/">Stylish</a> to use icon from "Private Window" button:
```css
/* AGENT_SHEET */ /* <- header for Stylish */
#privateTab-toolbar-openNewPrivateTab[cui-areatype="menu-panel"] {
	list-style-image: url("chrome://browser/skin/menuPanel.svg") !important;
	-moz-image-region: rect(0, 576px, 32px, 544px) !important;
}
```

Or just apply grayscale <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/filter">filter</a>:
```css
#privateTab-toolbar-openNewPrivateTab[cui-areatype="menu-panel"] {
	filter: grayscale(1);
}
```
