### ISSUE TITLE
Add ability to show "New Private Tab" button after "New Tab" button

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Private_Tab#90]
Requested here: https://addons.mozilla.org/addon/private-tab/reviews/495488/

We can use additional button (just like for built-in "New Tab" button):
![Screenshot: DOM nodes](https://f.cloud.github.com/assets/601488/938128/84bc8e50-00f5-11e3-88f5-6a1a04c11702.png)

and tricks like
chrome://browser/content/browser.css

``` css
#tabbrowser-tabs:not([overflow="true"]) ~ #alltabs-button,
#tabbrowser-tabs:not([overflow="true"]) + #new-tab-button,
#tabbrowser-tabs[overflow="true"] > .tabbrowser-arrowscrollbox > .tabs-newtab-button,
#TabsToolbar[currentset]:not([currentset*="tabbrowser-tabs,new-tab-button"]) > #tabbrowser-tabs > .tabbrowser-arrowscrollbox > .tabs-newtab-button,
#TabsToolbar[customizing="true"] > #tabbrowser-tabs > .tabbrowser-arrowscrollbox > .tabs-newtab-button {
  visibility: collapse;
}
```
